# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hrcx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hrcx.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nhrcx.proto\"n\n\x0bShareHeader\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x11\n\tthreshold\x18\x02 \x01(\x05\x12!\n\x05point\x18\x03 \x01(\x0b\x32\x12.ShareHeader.Point\x1a\x1d\n\x05Point\x12\t\n\x01X\x18\x01 \x01(\x05\x12\t\n\x01Y\x18\x02 \x01(\x0c\":\n\x0cStreamHeader\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x1a\n\x12\x65ncrypted_filename\x18\x03 \x01(\x0c\"\'\n\x0bStreamBlock\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x06proto3'
)




_SHAREHEADER_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='ShareHeader.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='ShareHeader.Point.X', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='ShareHeader.Point.Y', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=124,
)

_SHAREHEADER = _descriptor.Descriptor(
  name='ShareHeader',
  full_name='ShareHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ShareHeader.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='ShareHeader.threshold', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='ShareHeader.point', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SHAREHEADER_POINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=124,
)


_STREAMHEADER = _descriptor.Descriptor(
  name='StreamHeader',
  full_name='StreamHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='StreamHeader.header', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encrypted_filename', full_name='StreamHeader.encrypted_filename', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=184,
)


_STREAMBLOCK = _descriptor.Descriptor(
  name='StreamBlock',
  full_name='StreamBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StreamBlock.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='StreamBlock.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=225,
)

_SHAREHEADER_POINT.containing_type = _SHAREHEADER
_SHAREHEADER.fields_by_name['point'].message_type = _SHAREHEADER_POINT
DESCRIPTOR.message_types_by_name['ShareHeader'] = _SHAREHEADER
DESCRIPTOR.message_types_by_name['StreamHeader'] = _STREAMHEADER
DESCRIPTOR.message_types_by_name['StreamBlock'] = _STREAMBLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareHeader = _reflection.GeneratedProtocolMessageType('ShareHeader', (_message.Message,), {

  'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
    'DESCRIPTOR' : _SHAREHEADER_POINT,
    '__module__' : 'hrcx_pb2'
    # @@protoc_insertion_point(class_scope:ShareHeader.Point)
    })
  ,
  'DESCRIPTOR' : _SHAREHEADER,
  '__module__' : 'hrcx_pb2'
  # @@protoc_insertion_point(class_scope:ShareHeader)
  })
_sym_db.RegisterMessage(ShareHeader)
_sym_db.RegisterMessage(ShareHeader.Point)

StreamHeader = _reflection.GeneratedProtocolMessageType('StreamHeader', (_message.Message,), {
  'DESCRIPTOR' : _STREAMHEADER,
  '__module__' : 'hrcx_pb2'
  # @@protoc_insertion_point(class_scope:StreamHeader)
  })
_sym_db.RegisterMessage(StreamHeader)

StreamBlock = _reflection.GeneratedProtocolMessageType('StreamBlock', (_message.Message,), {
  'DESCRIPTOR' : _STREAMBLOCK,
  '__module__' : 'hrcx_pb2'
  # @@protoc_insertion_point(class_scope:StreamBlock)
  })
_sym_db.RegisterMessage(StreamBlock)


# @@protoc_insertion_point(module_scope)
